#!/bin/bash -e
# set ipconfig

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
[ -z "$IP_CONFIG" ] && exit 0
[ "$IP_CONFIG" != "manual" ] && [ "$IP_CONFIG" != "static" ] && [ "$IP_CONFIG" != "dhcp" ] && exit 1
[ ! -e /etc/network/interfaces ] && exit 1

APP=$(turnkey-version | cut -d "-" -f 2)

IP_IFACE="eth0"
[ "$APP" == "lxc" ] && IP_IFACE="br0"

# if IP_CONFIG is not changed skip this script and avoid a interface reconfiguration
grep "iface $IP_IFACE inet $IP_CONFIG" /etc/network/interfaces >/dev/null && exit 0

ifdown --exclude=lo -a

# since debian 8 (systemd) ifdown does no longer take the interface down
# if we change between manual, static or dhcp this does not work anymore
# as ifup won't do anything
ip link set $IP_IFACE down

# remove modified or unecessary options, regardless of order
  sed -i "/auto $IP_IFACE/,/^$/ {
  /hostname/ d
  /address/ d
  /netmask/ d
  /gateway/ d
  /dns-nameservers/ d
  }" /etc/network/interfaces

# configure 'manual' interface
if [ "$IP_CONFIG" = "manual" ]; then
  sed -i "/auto $IP_IFACE/,/^$/ {
  /iface/ s/[^ ]*$/manual/
  }" /etc/network/interfaces
fi

# configure 'dhcp' interface
if [ "$IP_CONFIG" = "dhcp" ]; then
  sed -i "/auto $IP_IFACE/,/^$/ {
  /iface/ s/[^ ]*$/dhcp/
  /iface/ a\\
    hostname $HOSTNAME
  }" /etc/network/interfaces
fi

# configure 'static' interface
if [ "$IP_CONFIG" = "static" ]; then
  sed -i "/auto $IP_IFACE/,/^$/ {
  /iface/ s/[^ ]*$/static/
  /iface/ a\\
    address $IP_ADDRESS\\
    netmask $IP_NETMASK\\
    gateway $IP_GW\\
    dns-nameservers $IP_DNS1 $IP_DNS2
  }" /etc/network/interfaces
fi

ifup --exclude=lo -a

exit $?
