#!/bin/bash
# auto grow filesystem for block device based appliances - (c) Aug/2014 by Peter Lieven <pl@kamp.de>

[[ -z "$_TURNKEY_INIT" ]] || exit 0

# shellcheck source=default/inithooks
source /etc/default/inithooks
if [[ -e "$INITHOOKS_CONF" ]]; then
    # shellcheck disable=SC1090
    source "$INITHOOKS_CONF"
fi

if [[ "$AUTOGROW" != "ONCE" ]] && [[ "$AUTOGROW" != "ALWAYS" ]]; then
   exit 0
fi
if [[ "$(dirname "$0")" == "/usr/lib/inithooks/everyboot.d" ]] \
    && [[ "$AUTOGROW" != "ALWAYS" ]]; then
        exit 0
fi

[[ -n "$AUTOGROW_DEV" ]] || AUTOGROW_DEV=/dev/vda
[[ -n "$AUTOGROW_PART" ]] || AUTOGROW_PART="${AUTOGROW_DEV}2"
[[ -n "$AUTOGROW_FS" ]] || AUTOGROW_FS=/dev/turnkey/root
[[ -n "$AUTOGROW_FS_ALWAYS" ]] || AUTOGROW_FS_ALWAYS=TRUE

DEVSIZE=$(blockdev --getsize "$AUTOGROW_DEV")

if [[ "0$DEVSIZE" -eq 0 ]]; then
   exit 1
fi

PARTINFO=$(sfdisk -d -uS "$AUTOGROW_DEV" \
    | grep -A1 "$AUTOGROW_PART" \
    | grep -v "$AUTOGROW_PART")
if [[ -n "$PARTINFO" ]]; then
    PARTINFO=${PARTINFO/:/ }
    PARTINFO=${PARTINFO//,/ }
    PARTINFO=${PARTINFO//=/ }
    if grep -s "start 0 size 0 Id 0" <<<"$PARTINFO"; then
        exit 1
    fi
fi

PARTINFO=$(sfdisk -d -uS "$AUTOGROW_DEV" | grep "$AUTOGROW_PART")
if [[ -z "$PARTINFO" ]]; then
   exit 1
fi

PARTINFO=${PARTINFO/:/ }
PARTINFO=${PARTINFO//,/ }
PARTINFO=${PARTINFO//=/ }
PARTINFOX=("${PARTINFO}")

if [[ "${PARTINFOX[0]}" != "$AUTOGROW_PART" ]] \
    || [[ "${PARTINFOX[1]}" != "start" ]] \
    || [[ "${PARTINFOX[3]}" != "size" ]]; then
        exit 1
fi
if [[ "${PARTINFOX[5]}" != "Id" ]] && [[ "${PARTINFOX[5]}" != "type" ]]; then
   exit 1
fi

START=${PARTINFOX[2]}
SIZE=${PARTINFOX[4]}
ID=${PARTINFOX[6]}

[ "$ID" != "8e" ] && exit 1

if [[ $((START + SIZE + 65536)) -lt "$DEVSIZE" ]]; then
    if [[ -e /var/tmp/autogrow.size ]] \
        && [[ "$(</var/tmp/autogrow.size)" -eq "$DEVSIZE" ]]; then
            exit 1
    fi
    echo "$DEVSIZE" > /var/tmp/autogrow.size
    sfdisk -d -uS "$AUTOGROW_DEV" | grep "${AUTOGROW_DEV}1" > /tmp/sfdisk.dump
    echo "$AUTOGROW_PART : start= $START, size= $((DEVSIZE - START)), ${PARTINFOX[5]}= $ID" \
        >> /tmp/sfdisk.dump
    sfdisk -uS --no-reread --force "$AUTOGROW_DEV" < /tmp/sfdisk.dump
    exit 42
elif [[ "$AUTOGROW_FS" != "SKIP" ]]; then
    if [[ -e /var/tmp/autogrow_fs.size ]] \
        && [[ $(</var/tmp/autogrow_fs.size) -eq $DEVSIZE ]]; then
            exit 0
    fi
    echo "$DEVSIZE" > /var/tmp/autogrow_fs.size
    pvresize "$AUTOGROW_PART"
    if [[ "$(dirname "$0")" == "/usr/lib/inithooks/everyboot.d" ]] \
        && [[ "$AUTOGROW_FS_ALWAYS" != "TRUE" ]]; then
            exit 0
    fi
    lvextend -l+100%FREE "$AUTOGROW_FS" 2>/dev/null || ERR=$?
    if [[ "$ERR" -eq 3 ]]; then
        exit 0
    fi
    if [[ $ERR -eq 0 ]] && resize2fs "$AUTOGROW_FS" && touch /forcefsck; then
        exit 42
    fi
fi
exit 1
