#!/bin/bash -e

[[ -z "$_TURNKEY_INIT" ]] || exit 0

# shellcheck source=default/inithooks
source /etc/default/inithooks
if [[ -e "$INITHOOKS_CONF" ]]; then
    # shellcheck disable=SC1090
    source "$INITHOOKS_CONF"
fi

if [[ "${SUDOADMIN,,}" == "true" ]]; then
    turnkey-sudoadmin on --disable-setpass
elif [[ "${SUDOADMIN,,}" == "false" ]]; then
    turnkey-sudoadmin off --disable-setpass
fi
