#!/bin/bash -e
# set root password

USERNAME=root

. /etc/default/inithooks
[ "$(echo $SUDOADMIN | tr [A-Z] [a-z] )" = "true" ] && USERNAME=admin

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/setpass.py $USERNAME --pass="$ROOT_PASS"

