#!/bin/bash -e
# set root password

# shellcheck source=default/inithooks
source /etc/default/inithooks
if [[ -e "$INITHOOKS_CONF" ]]; then
    # shellcheck disable=SC1090
    source "$INITHOOKS_CONF"
fi

USERNAME="root"
if [[ "${SUDOADMIN,,}" == "true" ]]; then
    USERNAME="admin"
fi

$INITHOOKS_PATH/bin/setpass.py $USERNAME --pass="$ROOT_PASS"
