#!/bin/bash -e

# Note that as of v19.0, the init-fence service is enabled by default

[[ -z "$_TURNKEY_INIT" ]] || exit 0

USERNAME=root
# shellcheck source=default/inithooks
source /etc/default/inithooks
USERNAME="root"
if [[ "${SUDOADMIN,,}" == "true" ]]; then
    USERNAME="admin"
fi

PROFILE_FIRSTLOGIN=$(eval printf ~$USERNAME)/.profile.d/turnkey-init-fence
if [[ -f "$PROFILE_FIRSTLOGIN" ]]; then
    chmod +x "$PROFILE_FIRSTLOGIN"
fi
