#!/bin/bash -e

systemctl disable turnkey-init-fence
systemctl stop turnkey-init-fence

# ONLY run this from within turnkey-init
    if [[ -n "$_TURNKEY_INIT" ]]; then
    for home in /root /home/admin; do
        if [[ -e $home/.profile.d/turnkey-init-fence ]]; then
            chmod -x $home/.profile.d/turnkey-init-fence
        fi
    done
    chmod -x /usr/lib/inithooks/firstboot.d/??turnkey-init-fence*
fi

echo "turnkey-init-fence is down"
