#!/bin/bash

[ -z "$_TURNKEY_INIT" ] && exit 0; # ONLY run from within turnkey-init

if systemctl is-active --quiet turnkey-init-fence; then

    systemctl disable turnkey-init-fence
    systemctl stop turnkey-init-fence

fi

for home in /root /home/admin; do
    [ -e $home/.profile.d/turnkey-init-fence ] && chmod -x $home/.profile.d/turnkey-init-fence;
done

chmod -x /usr/lib/inithooks/firstboot.d/??turnkey-init-fence*

echo 'turnkey-init-fence is down'
