#!/bin/bash -e

# shellcheck source=default/inithooks
source /etc/default/inithooks
if [[ -e "$INITHOOKS_CONF" ]]; then
    # shellcheck disable=SC1090
    source "$INITHOOKS_CONF"
fi

# blank out configuration file (usually contains passwords)
if [[ -e $INITHOOKS_CONF ]]; then
    echo > $INITHOOKS_CONF
fi

# set run_firstboot to false
sed -i "\|RUN_FIRSTBOOT| s|=.*|=false|" /etc/default/inithooks
