#!/bin/bash -e
# reboot system (kernel upgrade, set chmod +x by 95secupdates)
# will be skipped if running live or REBOOT set to SKIP

chmod -x "$0" # self-deactivating

# shellcheck source=default/inithooks
source /etc/default/inithooks
if [[ -e "$INITHOOKS_CONF" ]]; then
    # shellcheck disable=SC1090
    source "$INITHOOKS_CONF"
fi

if grep -qs boot=live /proc/cmdline; then
    exit 2
elif [[ "${REBOOT,,}" == "skip" ]]; then
    exit 0
fi

if [[ "${SEC_UPDATES,,}" == "force" ]]; then
    echo "rebooting due to kernel security upgrade..."
    reboot
fi
$INITHOOKS_PATH/bin/reboot-ask.py
