#!/usr/bin/python3
#
# Copyright (c) 2012-2015 Alon Swartz <alon@turnkeylinux.org>
# Copyright (c) 2016-2026 TurnKey GNU/Linux https://www.turnkeylinux.org
#
# This file is part of InitHooks.
#
# InitHooks is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at your
# option) any later version.
#
"""
Execute firstboot initialization hooks, skipping blacklisted scripts.

firstboot.d hook execution environment:

    _TURNKEY_INIT=1

"""
import os
import subprocess
import sys
from typing import NoReturn

from conffile import ConfFile


def fatal(e: str) -> NoReturn:
    print("error: " + str(e), file=sys.stderr)
    sys.exit(1)


def usage(e: str | None = None) -> NoReturn:
    if e:
        print("error: " + str(e), file=sys.stderr)

    print("Syntax: %s [-h|--help] [-c|--full-confconsole]\n" % (sys.argv[0]), file=sys.stderr)
    print(__doc__.strip(), file=sys.stderr)
    print("\nOptions:\n")
    print("  -h|--help             - print this help and exit")
    print("  -c|--full-confconsole - after initialization open full confconsole (default is basic).")
    print("                          If Confconsole not installed, will be ignored.")
    sys.exit(1)


class Config(ConfFile):
    CONF_FILE = "/etc/default/inithooks"


class InitHooks:
    def __init__(self, force_all_hooks: bool = False) -> None:
        self.conf = Config()
        self.force_all_hooks = force_all_hooks

    @staticmethod
    def _exec(cmd: str) -> None:
        env = os.environ.copy()
        env["PATH"] = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin"
        subprocess.run([cmd], env=env)

    def execute(self, dname) -> None:
        if not self.force_all_hooks:
            os.environ["_TURNKEY_INIT"] = "1"
        dpath = os.path.join(self.conf.inithooks_path, dname)
        if not os.path.exists(dpath):
            return

        scripts = os.listdir(dpath)
        scripts.sort()
        for fname in scripts:
            fpath = os.path.join(dpath, fname)
            if os.access(fpath, os.X_OK):
                self._exec(fpath)


def main() -> None:
    if os.geteuid() != 0:
        fatal("turnkey-init must be run with root permissions")

    confconsole = ["/usr/bin/confconsole"]
    if os.path.exists(confconsole[0]) and os.access(confconsole[0], os.X_OK):
        confconsole.append("--usage")
    else:
        # /bin/true ignores args and always returns true
        confconsole = ["/bin/true", "--null"]

    force_all_hooks = False

    args = sys.argv[1:]
    if args:
        for arg in args:
            if arg in ("-h", "--help"):
                usage()
            if arg in ("-c", "--full-confconsole"):
                confconsole = confconsole[:-1]
            if arg in ("-f", "--force"):
                force_all_hooks = True

    inithooks = InitHooks(force_all_hooks=force_all_hooks)
    inithooks.execute("firstboot.d")

    subprocess.run(confconsole)


if __name__ == "__main__":
    main()
