#!/bin/sh

set -e

mkdir -p /var/run/turnkey-init-fence
if [ -f /etc/default/turnkey-init-fence ]; then
    RUNAS=$(sed -n 's/^RUNAS=//p' /etc/default/turnkey-init-fence)
    if [ -n "$RUNAS" ]; then
        chown -R $RUNAS /var/run/turnkey-init-fence 
    fi
fi

chmod 755 /usr/lib/inithooks/bin/inithooks_cache.py

#DEBHELPER#

exit 0
